package com.lucas.compilador.objetos;

public enum Tipo {
    SPROGRAMA, SINICIO, SVAR, SFIM, SATRIBUICAO, STIPO, SESCREVA, SINTEIRO, SPONTO_E_VIRGULA, SPONTO, SVIRGULA, SMAIS,
    SMENOS, SMULTIPLICACAO, SDIVISAO, SNUMERO, SIDENTIFICADOR, SABRE_PARENTESIS, SFECHA_PARENTESIS, SCOMENTARIO, SERRO
}
